version: 2
jobs:
  build:
    orbs:
      - node: circleci/node@5.0.2
    steps:
      - checkout
      - run: echo "build"
  build2:
    orbs:
      - node: circleci/node@5.0.2
    steps:
      - checkout
      - run: echo "build2"
workflows:
    version: 2
    build1_build2:
      jobs:
        - build
        - build2

