version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "build"
  build2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "build2"
workflows:
    version: 2
    build1_build2:
      jobs:
        - build
        - build2

