version: 2
jobs:
  install:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: echo "npm install success"
  start:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - run: echo "npm buolding"
      - run: npm install
      - run: echo "npm install success"
      - run: npm build
      - run: echo "npm builded"
  useless:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - echo "hello"
workflows:
    version: 2
    install_start:
      jobs:
        - install
        - build
        - useless:
            requires:
              - build


